### ISSUE TITLE
yajl

### ISSUE THREAD

**Issue by xingzhong** [cdock1029/ceres#5]
yajl seems a fast json library. But we need install a non nodejs requirement.

Do we really heavily using that now?
Can we use build-in implementation or alternative method?

**Comment by cdock1029** [comment]
The issue is that the built in JSON parsing functionality of javascript is synchronous. Therefore yajil is a necessary component for asynchronous performance for parsing the JSON... if there is malformed JSON submitted to the application that is parsed by JSON.parse, the whole application would crash.. as well as for larger JSON objects performance would suffer vs asynchronous parsing.
