### ISSUE TITLE
cross-origin URL 

### ISSUE THREAD

**Issue by xingzhong** [cdock1029/ceres#6]
I am currently testing the service through a web application. The requests send from the apps get reject due to the cross-origin prevention. Can we set our response header to properly allow my app host to access the resources?

XMLHttpRequest cannot load http://light.home:9999/data. Origin http://dev.yesgoody.com is not allowed by Access-Control-Allow-Origin. 

http://stackoverflow.com/questions/14185383/cross-domain-cors-support-for-backbone-js

**Comment by linux-colonel** [comment]
First, I'm assuming that your web application is trying to make HTTP requests to CERES through client-side javascript running in the browser.  Is this correct?

Assuming this is the case, I have added the http header  'Access-Control-Allow-Origin': '*' on all responses.  This should allow data collection (putting data on the server), queries, and metrics to be requested from the browser.  Deleting and updating require DELETE and PUT requests (as per our API), so it would be more involved to implement CORS for these types of requests. I doubt I'd be able to get this done and tested by the end of the semester.   Please let us know how important it is to be able to do updates and deletes from client-side javascript.

I have committed the change, so please go ahead and test it. Data collection, queries, and metrics should work.

**Comment by xingzhong** [comment]
Today, I hope to test the api through the web client. Instead of the cross-origin url error, I get 400 bad request.

I push a very simple web page to the repo in test folder. 
What I want to do is get and post the data through ceres' api.
I am using jQuery to communicate to server. I think my problem is in the data encoding part.  
Here is my configuration. 

I disable the oauth. the local test through testrunner passed. 
On the other machine, I run a web server which host a client contains jquery.
I can tell the ceres server get the request from the log. But on client I get 400 bad request. 

Any idea to help me make the client request works?

**Comment by linux-colonel** [comment]
I found what the problem was and fixed it (the working client has been committed).  There were two issues:
1) The object being sent needed to be "stringified" first.  The server was seeing it as an "Object".
2) The framework you're using appears to be "smart" enough to URL encode POST requests, so the request ended up getting URL-encoded twice.  

I tested your web app against a server running on my local machine, and then I tested it against http://ceres-dev.yesgoody.com/data .  It should be working now, so please let us know if there are any other issues.

**Comment by xingzhong** [comment]
it works great! thanks
